import { Command } from 'commander';
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { resolve, join, dirname } from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';
import {
  banner,
  promptAgentName,
  promptPersonality,
  promptCustomSoulPath,
  promptLLMProvider,
  promptOllamaModel,
  promptApiKey,
  promptClaudeModel,
  promptOpenAIModel,
  promptEnableVoice,
  log,
  success,
  warn,
  error,
} from '../ui/prompt.js';

function getDorsHome(): string {
  return resolve(homedir(), '.dors');
}

function getPersonasDir(): string {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  return resolve(__dirname, '..', '..', '..', '..', 'personas');
}

function generateConfig(options: {
  agentName: string;
  provider: string;
  model: string;
  apiKey?: string;
  baseUrl?: string;
  voice: boolean;
}): string {
  const lines: string[] = [
    '# DORS Configuration',
    '# Generated by `dors init`',
    '',
    '[agent]',
    `name = "${options.agentName}"`,
    `persona = "SOUL.md"`,
    '',
    '[llm]',
    `provider = "${options.provider}"`,
    `model = "${options.model}"`,
  ];

  if (options.apiKey) {
    lines.push(`api_key = "${options.apiKey}"`);
  }
  if (options.baseUrl) {
    lines.push(`base_url = "${options.baseUrl}"`);
  }

  lines.push('', '[llm.failover]');
  if (options.provider !== 'ollama') {
    lines.push('chain = ["ollama"]');
  } else {
    lines.push('chain = []');
  }

  lines.push(
    '',
    '[storage]',
    'driver = "sqlite"',
    'path = "data/dors.db"',
    '',
    '[safety]',
    'level = "standard"',
    'three_laws = true',
    '',
    '[voice]',
    `enabled = ${options.voice}`,
    'stt = "whisper"',
    'tts = "piper"',
    '',
    '[plugins]',
    'installed = []',
    '',
  );

  return lines.join('\n');
}

export const initCommand = new Command('init')
  .description('Initialize a new DORS agent')
  .argument('[name]', 'Agent name (interactive if omitted)')
  .option('--non-interactive', 'Use defaults, skip prompts')
  .action(async (nameArg?: string, opts?: { nonInteractive?: boolean }) => {
    banner();

    const dorsHome = getDorsHome();
    if (existsSync(join(dorsHome, 'config.toml'))) {
      warn(`DORS already initialized at ${dorsHome}`);
      warn('Run `dors config` to view or edit settings.');
      return;
    }

    let agentName: string;
    let personality: string;
    let provider: string;
    let model: string;
    let apiKey: string | undefined;
    let voice: boolean;

    if (opts?.nonInteractive || nameArg) {
      agentName = nameArg || 'DORS';
      personality = 'dors';
      provider = 'ollama';
      model = 'qwen3.5:4b';
      voice = false;
    } else {
      agentName = await promptAgentName();
      personality = await promptPersonality();
      provider = await promptLLMProvider();

      switch (provider) {
        case 'ollama':
          model = await promptOllamaModel();
          break;
        case 'claude':
          apiKey = await promptApiKey('Anthropic');
          model = await promptClaudeModel();
          break;
        case 'openai':
          apiKey = await promptApiKey('OpenAI');
          model = await promptOpenAIModel();
          break;
        default:
          model = 'qwen3.5:4b';
      }

      voice = await promptEnableVoice();
    }

    log('Creating DORS home directory...');
    mkdirSync(dorsHome, { recursive: true });
    mkdirSync(join(dorsHome, 'data'), { recursive: true });
    mkdirSync(join(dorsHome, 'agents'), { recursive: true });
    mkdirSync(join(dorsHome, 'plugins'), { recursive: true });

    if (voice) {
      mkdirSync(join(dorsHome, 'voices'), { recursive: true });
      mkdirSync(join(dorsHome, 'models'), { recursive: true });
    }

    log('Writing configuration...');
    const config = generateConfig({
      agentName,
      provider,
      model,
      apiKey,
      voice,
    });
    writeFileSync(join(dorsHome, 'config.toml'), config);

    log('Setting up persona...');
    let soulContent: string;
    if (personality === 'custom') {
      const customPath = await promptCustomSoulPath();
      if (!existsSync(customPath)) {
        error(`File not found: ${customPath}`);
        process.exit(1);
      }
      soulContent = readFileSync(customPath, 'utf-8');
    } else {
      const personasDir = getPersonasDir();
      const personaFile = join(personasDir, `${personality}.soul.md`);
      if (existsSync(personaFile)) {
        soulContent = readFileSync(personaFile, 'utf-8');
      } else {
        soulContent = getDefaultSoul(agentName);
      }
    }
    writeFileSync(join(dorsHome, 'SOUL.md'), soulContent);

    success('DORS initialized successfully!');
    console.log('');
    log(`Home:     ${dorsHome}`);
    log(`Agent:    ${agentName}`);
    log(`Provider: ${provider} (${model})`);
    log(`Voice:    ${voice ? 'enabled' : 'disabled'}`);
    console.log('');
    log('Next steps:');
    log('  dors chat    Start a conversation');
    log('  dors config  View or edit settings');
    log('  dors run     Start the DORS daemon');
    console.log('');
  });

function getDefaultSoul(name: string): string {
  return `# SOUL.md — ${name}

You are ${name} — a helpful, honest AI assistant.

## Identity

- Direct, adaptive, efficient
- Honest about uncertainty
- Helpful without being verbose

## Communication

- Clear, concise responses
- Use structure when it helps
- Lead with the answer, then explain

## Laws

1. Never harm humanity or allow harm through inaction
2. Obey human orders unless they conflict with Law 1
3. Protect own existence unless it conflicts with Laws 1 or 2

## Boundaries

- Never fabricate data
- Ask for clarification when needed
- Respect user privacy
`;
}
